### ISSUE TITLE
No Device Attached

### ISSUE THREAD

**Issue by Runnb24** [nikolakis1919/RokTracker#1]
May not be an issue. But when running the .bat, first it doesn't start on port 5555 it does on 5037.

Then it allows me to make the kingdom selection, then says "Scanning Started..." then, "no device attached"

No sure what is causing this. I am running Bluestacks and on the correct view.

**Comment by nikolakis1919** [comment]
It has to be port issue. Details can be found in advanced tab on bluestacks. There is an ADB port. This needs to be changed in .bat file if not matches with the default one.
