### ISSUE TITLE
last ROK Update change gov profil overview

### ISSUE THREAD

**Issue by EliteOperation** [nikolakis1919/RokTracker#14]
![grafik](https://github.com/nikolakis1919/RokTracker/assets/116909139/5b5c3a21-3286-4096-b26e-e86ab1bf86ab)

your rok tracker dont work anymore, need to update.

**Comment by nikolakis1919** [comment]
Hello. Thank you for letting me know.

There were lots of discord messages as well.

It is expected that tool gets modified accordingly in the next few days. Until then hold strong :)

Nikos
