### ISSUE TITLE
scikit_learn version problem

### ISSUE THREAD

**Issue by leonyonz** [nikolakis1919/RokTracker#15]
Hello, i facing issue when fresh installing the tools.

It seems the problem related to  scikit_learn==0.22 from requirement.txt.

After i reinstall the module with the new ones (0.24) the tools running well.

![Screenshot_43](https://github.com/nikolakis1919/RokTracker/assets/42370275/8db3daf1-5a63-4a7a-8056-979e38a1845f)

**Comment by nikolakis1919** [comment]
New requirements.txt file is uploaded and issue was solved. Thank you.
