### ISSUE TITLE
OCR issue with 3 numbers

### ISSUE THREAD

**Issue by ShawnCrocker** [nikolakis1919/RokTracker#19]
In the last 3 scans 3 errors happened consistently for the same values and Governors.

t2 kills
2,207 -> 22

07

t5 kills + t2 kills (happens twice, single 1 is OK for t3 kills)
single 1 -> space

t1 kills (happens once,  ok for t2 and t5 kills)
Single 2 -> 0

Thanks

**Comment by ShawnCrocker** [comment]
I can share more on Discord (PurpleFlaps, we've chatted before)

**Comment by nikolakis1919** [comment]
It should be fixed in the upcoming version.

Thank you for your support.
