### ISSUE TITLE
skips

### ISSUE THREAD

**Issue by milkorlife** [nikolakis1919/RokTracker#20]
Sometimes it omits some people in top, not sure what's the cause yet might be misclick or going too fast to next. I was generous and gave it 4 cores and 8gb ram but still same . (I did see it miss clicking before)

**Comment by nikolakis1919** [comment]
Maybe you clicked resume scan option. This option should be clicked only when you want to start scanning from the middle of the screen(if it crashes or stops and you want to resume).

**Comment by milkorlife** [comment]
Sadly , no :( 300  scan, will record it and send on discord , maybe you can tell what i messed up. 

EDIT
Well im silly. Apparently pressing stuff that's keybinded in bluestacks is bad idea. Suggestion : disable keybinds for scan , add for tutorial for noblets like me.
