### ISSUE TITLE
Flagged by McAfee AV

### ISSUE THREAD

**Issue by Woltharius2884** [nikolakis1919/RokTracker#23]
When I tried to launch the Kingdom Scanner GUI, McAfee Anti-virus flagged the .exe and quarantined it as potential threat (virus or unwanted). Has anyone else run into this? I successfully ran the scan multiple times in the past before this happened, but this just started a week ago. Any thoughts? Reinstall?

Edit: Problem solved. McAfee uninstalled. :)

**Comment by nikolakis1919** [comment]
Each AV has an exception list, so you can add the folder in exception list to always ignore it when scanning for treat.
