### ISSUE TITLE
After update not work

### ISSUE THREAD

**Issue by MeHDakc** [nikolakis1919/RokTracker#24]
RIP

**Comment by MeHDakc** [comment]
It scan one player in loop

**Comment by ybrazil** [comment]
same issue

**Comment by nikolakis1919** [comment]
Hello. Please join the [discord server](https://discord.gg/CvU96gVfjS) to describe the problem. For me, it's working fine.

Thank you.

**Comment by nikolakis1919** [comment]
Adjusted the time between clicks to stabilize the tool. Please update to new version.

Thank you.
