### ISSUE TITLE
Issue with KVK stats display being visible

### ISSUE THREAD

**Issue by OneVs4** [nikolakis1919/RokTracker#25]
Hello, I love your tool and since the recent update there was one tiny problem for me, the new KVK stats system struggles to analyze data when the stats are visible and not hidden, I think this has to do with the button to extend killpoints overlapping and as there is a small delay after clicking out of the KVK data button, the 

-> Line 236 :
```
            for _ in range(2):
                device.shell(f'input tap 1118 314')
```

loop seems not to be enough and it just skips the killpoints tiers analysis unless the player has kvk stats hidden, as that allows the killpoints button to be clicked in time. I figured adding some delay

```
            for _ in range(2):
                time.sleep(0.5)
                device.shell(f'input tap 1118 314')
```

fixes my issue.

Maybe I did something wrong when setting up the tool ?
Thanks!

The button I'm talking about :
![Capture d'écran 2024-08-14 175742](https://github.com/user-attachments/assets/d8725273-c38c-4509-90bc-016f6ca66020)

**Comment by nikolakis1919** [comment]
New version has been uploaded. Please check with this one. This one, should not be affected by computer's speed.

Thank you.
