### ISSUE TITLE
Big Scans skips Players

### ISSUE THREAD

**Issue by EliteOperation** [nikolakis1919/RokTracker#3]
Hello,

i scan TOP 300 Power Ranglist. But in the Sheet only 298 Player listed. I figured out, that the Tracker skip around player number 63.
Examble:
The Player 63 in TOP Power Ranglist.
Did not scanned.
But Player 62 and 64 are scanned.

So Every (like) 63 Players the Tracker skip a player. Thats why i have only 298 Players in the Sheet when i scanned 300.

In a 50er Scan. There are no problems.

Hope u understand and can help me. :)
Thank you!

**Comment by nikolakis1919** [comment]
Hi there,

In game there is a rule that you cannot locate someone's castle if he is inactive for more than some days, don't know exactly what is this number. Please make sure you can click the missing player in rankings manually.
If you are able to open his governor page, just reply in this post.

Thank you for your support.
