### ISSUE TITLE
.bat appears to have problems?

### ISSUE THREAD

**Issue by WillyTee** [nikolakis1919/RokTracker#6]
Afraid I'm a complete novice with programming etc, but I believe I installed everything I needed to and followed your steps, but seem to be stumped. I notice when I run the .bat it comes up with a number of errors and I'm not sure how to solve them?
![Screenshot 2023-01-23 074209](https://user-images.githubusercontent.com/123356992/213988165-fa1684dc-6d1a-4a58-b4f2-9dce7dcfea8f.jpg)

**Comment by theCyberTech** [comment]
The first error indicates that either:

1. pip is not installed in your python environment
2. pip is not in correct path.

Can you run the following from the command line and post the output as this will determine your current Python version

1. python -V

In the interim you can run the following from the command line as this will attempt to install pip if it is not already installed

1. python -m ensurepip --upgrade

Let us know how you go

**Comment by nikolakis1919** [comment]
@theCyberTech Said everything. Add to path option in python installer wasn't clicked. You will need to reinstall python from the installer. Make sure, this time, you click Add to path option.

**Comment by WillyTee** [comment]
Thank you for your replies guys, I really appreciate it and apologies for being such a novice.

I reinstalled python and definitely clicked add to path (pretty sure I did last time too), but seeing the same responses.

Again, apologies I'm so ill informed, but; do I use the command lines @theCyberTech suggests in windows command prompt?

edit: Ok, yep, put that in command prompt and seemed to work to do something, but still receiving the same responses from the .bat file

p.s. Python version 3.6.8, the one linked on the page I believe?

**Comment by theCyberTech** [comment]
Please run the following via command prompt:

python -m ensurepip --upgrade

Then try running BAT file again, any issues please screenshot and post here

**Comment by nikolakis1919** [comment]
@WillyTee Please contact me on discord to solve your issue asap. 
nikos#4469

**Comment by WillyTee** [comment]
Ha, I tried finding your discord and failed at that too! :p 

Do I just search for that in discord somewhere? Is there a way to send me a link?  Thank you for all your help

**Comment by nikolakis1919** [comment]
I cannot find you without giving me some information. Please leave your discord name.

**Comment by nikolakis1919** [comment]
I cannot find you without any information. Please let me know your discord name.

**Comment by WillyTee** [comment]
ooooohh, sorry, I'm a muppet. You mean DM on discord, and I was looking for a server. I will contact you shortly, thank you for all your patience and assistance!
