### ISSUE TITLE
[ASK] Want to remove some feature in my desktop

### ISSUE THREAD

**Issue by leonyonz** [nikolakis1919/RokTracker#9]
Hi Nikolakis,

Sorry to bother you, maybe this is a stupid question but i still want to know about it.

In case i want to record only Gov Name, Gov ID, and Gov Power, and skip KP (T1/T2/T3/T4/T5), dead, and resource gathered. which part of code that should i remove ?

Again, sorry if this questions bother you.

**Comment by securehst** [comment]
In the roktracker.py you would change 

```#Initialize Excel Sheet Header
sheet1.write(0, 0, 'Governor Name', style)
sheet1.write(0, 1, 'Governor ID', style)
sheet1.write(0, 2, 'Power', style)
sheet1.write(0, 3, 'Kill Points', style)
sheet1.write(0, 4, 'Deads', style)
sheet1.write(0, 5, 'Tier 1 Kills', style)
sheet1.write(0, 6, 'Tier 2 Kills', style)
sheet1.write(0, 7, 'Tier 3 Kills', style)
sheet1.write(0, 8, 'Tier 4 Kills', style)
sheet1.write(0, 9, 'Tier 5 Kills', style)
sheet1.write(0, 10,'Rss Assistance', style)
sheet1.write(0, 11,'Alliance', style)
```

```
#Initialize Excel Sheet Header
sheet1.write(0, 0, 'Governor Name', style)
sheet1.write(0, 1, 'Governor ID', style)
sheet1.write(0, 2, 'Power', style)
sheet1.write(0, 3, 'Kill Points', style)
sheet1.write(0, 4,'Alliance', style)
```

This may work.

**Comment by leonyonz** [comment]
Thank you, 

I have edit some line, can you review it ? [https://pastebin.com/bqYrH6rL](https://pastebin.com/bqYrH6rL)

**Comment by nikolakis1919** [comment]
Hello there!

Your question seems to be about kingdom power calculation without considering any of the rest stats.
Here is a version that can make everything much faster...

Please download, extract, drag and drop into roktracker folder and rename the file to roktracker.py or just edit in .bat file roktracker.py to roktracker_id_name_power.py
[roktracker_id_name_power.zip](https://github.com/nikolakis1919/RokTracker/files/11115031/roktracker_id_name_power.zip)

**Comment by EliteOperation** [comment]
> Hello there!
> 
> Your question seems to be about kingdom power calculation without considering any of the rest stats. Here is a version that can make everything much faster...
> 
> Please download, extract, drag and drop into roktracker folder and rename the file to roktracker.py or just edit in .bat file roktracker.py to roktracker_id_name_power.py [roktracker_id_name_power.zip](https://github.com/nikolakis1919/RokTracker/files/11115031/roktracker_id_name_power.zip)

i tested your "fast" version. but it dont work for me. i drag and drop it to the roktracker folder and copy the .bat file and rename it to roktracker_id_name_power also in the .bat file (roktracker.py to roktracker_id_name_power.py).
When i start it, this will come up on the first player scan:
![grafik](https://user-images.githubusercontent.com/116909139/229746991-18eacab4-d41d-43f7-88d2-5c0a5eeffc35.png)

What did i wrong?

**Comment by nikolakis1919** [comment]
File updated. Thanks for mentioning...
[roktracker_id_name_power.zip](https://github.com/nikolakis1919/RokTracker/files/11156991/roktracker_id_name_power.zip)

**Comment by leonyonz** [comment]
Wow thank you very much, this tools really help me alot to tracking governor power (increase/decrease) mostly used for pre & after kvk.

**Comment by leonyonz** [comment]
anyway, as you know bluestack ADB port is randomly generated, and every open this APP i need to utilize .bat file to make it works..

Is it possible to add some GUI form for ADB Port ?

**Comment by nikolakis1919** [comment]
It will be added in future updates :)
